### PR TITLE
Rename permissive-binary-license-1.0.txt to LICENSE-permissive-binary…

### PR DESCRIPTION
**Pull request by jlovejoy**
change filename to "LICENSE-..." so that it appears next to the informational license.txt file (alphabetically) and is generally more obvious /easy to see

### CODE REVIEW

**Comment by pjbakker** [comment]
Changing the name there also requires changing it in the files it is referenced to (LICENSE, and the headers)

**Comment by pjbakker** [comment]
@SeppoTakalo are you able to change it in your scripting run?

**Comment by SeppoTakalo** [comment]
Please do not merge this.
This repository is fully generated by script, so any modifications will be lost in the next release.

I will update scripts in the source repository https://github.com/ARMmbed/sal-stack-nanostack-private

**Comment by SeppoTakalo** [comment]
Updated the generator scripts in this PR: https://github.com/ARMmbed/sal-stack-nanostack-private/pull/592

Closing this.
Thank you.

**Pull request closed without merging**
